"""create_news_sources_feeds_and_ingestion_runs

Revision ID: 3e1fb3b9558e
Revises: 3fa334c77618
Create Date: 2026-10-05 10:03:25.538070

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3e1fb3b9558e'
down_revision: Union[str, Sequence[str], None] = '3fa334c77618'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('news_sources',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('slug', sa.String(length=255), nullable=False),
    sa.Column('website_url', sa.String(length=1024), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('logo_url', sa.String(length=1024), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_sources_slug'), 'news_sources', ['slug'], unique=True)
    op.create_table('news_feeds',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('feed_url', sa.String(length=1024), nullable=False),
    sa.Column('feed_type', sa.String(length=20), nullable=False),
    sa.Column('language', sa.String(length=10), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('default_topic_id', sa.UUID(), nullable=True),
    sa.Column('last_fetched_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['default_topic_id'], ['topics.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['news_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_news_feeds_default_topic_id'), 'news_feeds', ['default_topic_id'], unique=False)
    op.create_index(op.f('ix_news_feeds_feed_url'), 'news_feeds', ['feed_url'], unique=False)
    op.create_index(op.f('ix_news_feeds_source_id'), 'news_feeds', ['source_id'], unique=False)
    op.create_table('ingestion_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('feed_id', sa.UUID(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('articles_fetched', sa.Integer(), nullable=False),
    sa.Column('articles_created', sa.Integer(), nullable=False),
    sa.Column('duplicates_found', sa.Integer(), nullable=False),
    sa.Column('errors_count', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['feed_id'], ['news_feeds.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_ingestion_runs_feed_id'), 'ingestion_runs', ['feed_id'], unique=False)
    op.create_index(op.f('ix_ingestion_runs_status'), 'ingestion_runs', ['status'], unique=False)
    op.add_column('articles', sa.Column('source_id', sa.UUID(), nullable=True))
    op.add_column('articles', sa.Column('feed_id', sa.UUID(), nullable=True))
    op.add_column('articles', sa.Column('canonical_url', sa.String(length=1024), nullable=True))
    op.add_column('articles', sa.Column('ingestion_method', sa.String(length=20), server_default='MANUAL', nullable=False))
    op.create_index(op.f('ix_articles_canonical_url'), 'articles', ['canonical_url'], unique=False)
    op.create_index(op.f('ix_articles_feed_id'), 'articles', ['feed_id'], unique=False)
    op.create_index(op.f('ix_articles_ingestion_method'), 'articles', ['ingestion_method'], unique=False)
    op.create_index(op.f('ix_articles_source_id'), 'articles', ['source_id'], unique=False)
    op.create_foreign_key('fk_articles_feed_id_news_feeds', 'articles', 'news_feeds', ['feed_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_articles_source_id_news_sources', 'articles', 'news_sources', ['source_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'articles', type_='foreignkey')
    # WARNING: constraint name is None; this directive will fail as
    # rendered.  Add a name, or use a naming convention; see
    # https://alembic.sqlalchemy.org/en/latest/naming.html
    op.drop_constraint(None, 'articles', type_='foreignkey')
    op.drop_index(op.f('ix_articles_source_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_ingestion_method'), table_name='articles')
    op.drop_index(op.f('ix_articles_feed_id'), table_name='articles')
    op.drop_index(op.f('ix_articles_canonical_url'), table_name='articles')
    op.drop_column('articles', 'ingestion_method')
    op.drop_column('articles', 'canonical_url')
    op.drop_column('articles', 'feed_id')
    op.drop_column('articles', 'source_id')
    op.drop_index(op.f('ix_ingestion_runs_status'), table_name='ingestion_runs')
    op.drop_index(op.f('ix_ingestion_runs_feed_id'), table_name='ingestion_runs')
    op.drop_table('ingestion_runs')
    op.drop_index(op.f('ix_news_feeds_source_id'), table_name='news_feeds')
    op.drop_index(op.f('ix_news_feeds_feed_url'), table_name='news_feeds')
    op.drop_index(op.f('ix_news_feeds_default_topic_id'), table_name='news_feeds')
    op.drop_table('news_feeds')
    op.drop_index(op.f('ix_news_sources_slug'), table_name='news_sources')
    op.drop_table('news_sources')
    # ### end Alembic commands ###
